### ISSUE TITLE
what upstream revision is this based on?

### ISSUE THREAD

**Issue by ahundt** [indraforyou/keras_tfrecord#2]
This looks like it is partly based on the [keras master branch /keras/engine/training.py](https://github.com/fchollet/keras/blob/4fa7e5d454dd4f3f33f1d756a2a8659f2e789141/keras/engine/training.py#L643-L650). Is that the exact correct version or is it an older/newer one or perhaps from the keras-2 branch? 

The reason I ask is because I'm looking into if extending `model.fit()` and `model.fit_generator()` with multiple backends (tfrecord and the current hdf5) might be sensible.

**Comment by indraforyou** [comment]
Yes its based on a bit older version of Keras (1.1.2) which I have locally which as several local changes. But this version so support both tensorflow and theano backends.

**Comment by ahundt** [comment]
okay, awesome! I've submitted a pull request for this to keras-contrib https://github.com/farizrahman4u/keras-contrib/pull/27 and hope to make some extensions there.

**Comment by indraforyou** [comment]
Thanks for taking care of that.
